-------------------------------------------------------------------------------
Test set: com.dao.UserDaoTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 3.027 s <<< FAILURE! - in com.dao.UserDaoTest
updateUserTest(com.dao.UserDaoTest)  Time elapsed: 0.998 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.updateUserTest(UserDaoTest.java:53)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.updateUserTest(UserDaoTest.java:53)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.updateUserTest(UserDaoTest.java:53)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.updateUserTest(UserDaoTest.java:53)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.dao.UserDaoTest.updateUserTest(UserDaoTest.java:53)

selectUserTest(com.dao.UserDaoTest)  Time elapsed: 1.014 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [D:\fos\target\classes\mapper\UserDao.xml]
### The error may involve com.dao.UserDao.selectUser
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.selectUserTest(UserDaoTest.java:21)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [D:\fos\target\classes\mapper\UserDao.xml]
### The error may involve com.dao.UserDao.selectUser
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.selectUserTest(UserDaoTest.java:21)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.selectUserTest(UserDaoTest.java:21)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.selectUserTest(UserDaoTest.java:21)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.dao.UserDaoTest.selectUserTest(UserDaoTest.java:21)

insertUserTest(com.dao.UserDaoTest)  Time elapsed: 0.999 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.insertUserTest(UserDaoTest.java:42)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.insertUserTest(UserDaoTest.java:42)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.insertUserTest(UserDaoTest.java:42)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.dao.UserDaoTest.insertUserTest(UserDaoTest.java:42)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.dao.UserDaoTest.insertUserTest(UserDaoTest.java:42)

